services:
    _defaults:
      public: true

    ## Category services
    # Category repository
    prestashop.module.asblog.category.repository:
      class: PrestaShop\Module\AsBlog\Repository\CategoryRepository
      arguments:
        $connection: '@doctrine.dbal.default_connection'
        $dbPrefix: '%database_prefix%'
        $languages: '@=service("prestashop.adapter.legacy.context").getLanguages(true, service("prestashop.adapter.shop.context").getContextShopID())'
        $translator: '@translator'

    prestashop.module.asblog.category.form_type:
        class: PrestaShop\Module\AsBlog\Form\Type\CategoryType
        parent: 'form.type.translatable.aware'
        public: true
        tags:
            - { name: form.type }
        arguments:
          $parentCategoryChoices: '@=service("prestashop.module.asblog.category.choice_provider.parent_category").getChoices()'

    prestashop.module.asblog.category.parent_category.form_type:
      class: PrestaShop\Module\AsBlog\Form\Type\ParentCategoryChoiceTreeType
      arguments:
        - '@=service("prestashop.module.asblog.category.choice_provider.parent_category").getChoices()'
      tags:
        - { name: form.type }

    prestashop.module.asblog.category.choice_provider.parent_category:
        class: PrestaShop\Module\AsBlog\Form\ChoiceProvider\ParentCategoryChoiceProvider
        arguments:
          $connection: '@doctrine.dbal.default_connection'
          $dbPrefix: '%database_prefix%'
          $idLang: '@=service("prestashop.adapter.legacy.context").getLanguage().id'
          $shopIds: '@=service("prestashop.adapter.shop.context").getContextListShopID()'


    # Category form handler
    prestashop.module.asblog.category.form_handler:
        class: PrestaShop\PrestaShop\Core\Form\FormHandler
        arguments:
            $formBuilder: '@=service("form.factory").createBuilder()'
            $hookDispatcher: '@prestashop.core.hook.dispatcher'
            $formDataProvider: '@prestashop.module.asblog.category.form_provider'
            $formTypes:
                'category': 'PrestaShop\Module\AsBlog\Form\Type\CategoryType'
            $hookName: 'AdminPostCategoryWidget'

    # Category form data provider
    prestashop.module.asblog.category.form_provider:
        class: PrestaShop\Module\AsBlog\Form\CategoryFormDataProvider
        arguments:
            $repository: '@prestashop.module.asblog.category.repository'
            $moduleRepository: '@prestashop.core.admin.module.repository'
            $languages: '@=service("prestashop.adapter.legacy.context").getLanguages(true, service("prestashop.adapter.shop.context").getContextShopID())'
            $shopId: '@=service("prestashop.adapter.shop.context").getContextShopID()'
            $configuration: '@prestashop.adapter.legacy.configuration'


  ## Category Grid
  # Grid data query builder
    prestashop.module.asblog.category.grid.query_builder:
      class: PrestaShop\Module\AsBlog\Core\Grid\Query\CategoryQueryBuilder
      arguments:
        $connection: '@doctrine.dbal.default_connection'
        $dbPrefix: '%database_prefix%'

  # Grid Data Factory
    prestashop.module.asblog.category.grid.data_factory:
      class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
      arguments:
        $gridQueryBuilder: '@prestashop.module.asblog.category.grid.query_builder'
        $hookDispatcher: '@prestashop.core.hook.dispatcher'
        $queryParser: '@prestashop.core.grid.query.doctrine_query_parser'
        $gridId: 'category'

  # Grid Factory
    prestashop.module.asblog.category.grid.factory:
      class: PrestaShop\Module\AsBlog\Core\Grid\CategoryGridFactory
      arguments:
        $translator: '@translator'
        $hookDispatcher: '@prestashop.core.hook.dispatcher'
        $dataFactory: '@prestashop.module.asblog.category.grid.data_factory'
        $filterFormFactory: '@prestashop.core.grid.filter.form_factory'

