services:
    _defaults:
        public: true

    ## Post services
    # Post repository
    prestashop.module.asblog.post.repository:
        class: PrestaShop\Module\AsBlog\Repository\PostRepository
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $dbPrefix: '%database_prefix%'
            $languages: '@=service("prestashop.adapter.legacy.context").getLanguages(true, service("prestashop.adapter.shop.context").getContextShopID())'
            $translator: '@translator'

    # Post form data provider
    prestashop.module.asblog.form_provider:
        class: PrestaShop\Module\AsBlog\Form\PostFormDataProvider
        arguments:
            $repository: '@prestashop.module.asblog.repository'
            $moduleRepository: '@prestashop.core.admin.module.repository'
            $languages: '@=service("prestashop.adapter.legacy.context").getLanguages(true, service("prestashop.adapter.shop.context").getContextShopID())'
            $shopId: '@=service("prestashop.adapter.shop.context").getContextShopID()'
            $configuration: '@prestashop.adapter.legacy.configuration'

    # Post form handler
    prestashop.module.asblog.form_handler:
        class: PrestaShop\PrestaShop\Core\Form\FormHandler
        arguments:
            $formBuilder: '@=service("form.factory").createBuilder()'
            $hookDispatcher: '@prestashop.core.hook.dispatcher'
            $formDataProvider: '@prestashop.module.asblog.form_provider'
            $formTypes:
                'post': 'PrestaShop\Module\AsBlog\Form\Type\PostType'
            $hookName: 'AdminLinkWidget'

    prestashop.module.asblog.form_type:
        class: PrestaShop\Module\AsBlog\Form\Type\PostType
        parent: 'form.type.translatable.aware'
        public: true
        tags:
            - { name: form.type }

    ## Post grid

    # Grid data query builder
    prestashop.module.asblog.grid.query_builder:
        class: PrestaShop\Module\AsBlog\Core\Grid\Query\PostQueryBuilder
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $dbPrefix: '%database_prefix%'

    # Grid Data Factory
    prestashop.module.asblog.grid.data_factory:
        class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
        arguments:
            $gridQueryBuilder: '@prestashop.module.asblog.grid.query_builder'
            $hookDispatcher: '@prestashop.core.hook.dispatcher'
            $queryParser: '@prestashop.core.grid.query.doctrine_query_parser'
            $gridId: 'post'

    # Grid Factory
    prestashop.module.asblog.grid.factory:
        class: PrestaShop\Module\AsBlog\Core\Grid\PostGridFactory
        arguments:
            $translator: '@translator'
            $hookDispatcher: '@prestashop.core.hook.dispatcher'
            $dataFactory: '@prestashop.module.asblog.grid.data_factory'
            $filterFormFactory: '@prestashop.core.grid.filter.form_factory'

    ## Category services
    # Category repository
    prestashop.module.asblog.category.repository:
      class: PrestaShop\Module\AsBlog\Repository\CategoryRepository
      arguments:
        $connection: '@doctrine.dbal.default_connection'
        $dbPrefix: '%database_prefix%'
        $languages: '@=service("prestashop.adapter.legacy.context").getLanguages(true, service("prestashop.adapter.shop.context").getContextShopID())'
        $translator: '@translator'
