services:
    _defaults:
        public: true

    ## Post services
    # Post repository
    prestashop.module.as_blog.repository:
        class: PrestaShop\Module\AsBlog\Repository\PostRepository
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $dbPrefix: '%database_prefix%'
            $languages: '@=service("prestashop.adapter.legacy.context").getLanguages(true, service("prestashop.adapter.shop.context").getContextShopID())'
            $translator: '@translator'

    # Post form data provider
    prestashop.module.as_blog.form_provider:
        class: PrestaShop\Module\AsBlog\Form\PostFormDataProvider
        arguments:
            $repository: '@prestashop.module.as_blog.repository'
            $moduleRepository: '@prestashop.core.admin.module.repository'
            $languages: '@=service("prestashop.adapter.legacy.context").getLanguages(true, service("prestashop.adapter.shop.context").getContextShopID())'
            $shopId: '@=service("prestashop.adapter.shop.context").getContextShopID()'
            $configuration: '@prestashop.adapter.legacy.configuration'

    # Post form handler
    prestashop.module.as_blog.form_handler:
        class: PrestaShop\Core\Form\FormHandler
        arguments:
            $formBuilder: '@=service("form.factory").createBuilder()'
            $hookDispatcher: '@prestashop.core.hook.dispatcher'
            $formDataProvider: '@prestashop.module.as_blog.form_provider'
            $formTypes:
                'post': 'PrestaShop\Module\AsBlog\Form\Type\PostType'
